# render.yaml (Final Corrected Version)

services:
  # 1. The Redis instance for Celery
  - name: odysseus-redis
    type: redis
    plan: free 
    ipAllowList: [] 

  # 2. The main FastAPI Web Service
  - name: odysseus-api
    type: web
    runtime: python
    plan: starter 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --workers 8 --worker-class uvicorn.workers.UvicornWorker"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: odysseus-redis
          property: connectionString # <-- Correct property name

  # 3. The Celery Background Worker
  - name: odysseus-worker
    type: worker
    runtime: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A tasks.celery_app worker --loglevel=info -P gevent -c 100" # <-- CHANGE THIS
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: odysseus-redis
          property: connectionString # <-- Correct property name
